spring:
    application:
        name: novizit-message-service
    datasource:
        url: jdbc:mysql://novizit-mysql-server.mysql.database.azure.com:3306/app_messaging
        username: novizit
        password: Apple@2024
#        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect      
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411
#RABBIT MQ SETUP...
    # rabbitmq:
    #     host: localhost
    #     username: guest
    #     port: 5672
    #     password: guest
    #     user: 
    #         queue: user-queue                   
    #         exchange: user-exchange
    #         routing:
    #             key: user-queue
                            
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    # instance:
    #     hostname: ${EUREKA_HOST:localhost}     
    #OPEN API CUSTOM PATH
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
