spring:
    datasource:
        url: jdbc:mysql://novizit-mysql-server.mysql.database.azure.com:3306/posts
        username: novizit
        password: Apple@2024
#        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect      
    zipkin:
        base-url: https://${ZIPKIN_HOST:localhost}:9411                
eureka:
    client:
        service-url:
            defaultZone: https://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        nonSecurePortEnabled: false
        securePortEnabled: true
        statusPageUrl: https://${eureka.hostname}:${server.port}/actuator/info
        healthCheckUrl: https://${eureka.hostname}:${server.port}/health
        homePageUrl: https://${eureka.hostname}:${server.port}/
        #hostname: ${EUREKA_HOST:localhost}     